version: '3'

services:
    python:        
        image: python:3.8
        volumes: 
            - .:/workspace        
        tty: true    
        stdin_open: true
        ports: 
            - "5000:5000"