version: '3'

services:
  postgres:
    image: postgres:12
    container_name: python-postgres-example
    environment:
      - POSTGRES_PASSWORD=1234
    expose:
      - '54320'
    ports:
      - '54320:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./home:/home
    restart: always

volumes: 
  pgdata:
